/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author 84327
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btHoaDon = new javax.swing.JButton();
        btThucDon = new javax.swing.JButton();
        btBan = new javax.swing.JButton();
        btKhachHang = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        btOrder = new javax.swing.JButton();
        btVoucher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÍ BÁN THỨC ĂN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 70, 470, 80);

        btHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btHoaDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/hoadon.png"))); // NOI18N
        btHoaDon.setText("QUẢN LÍ  HÓA ĐƠN");
        btHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });
        jPanel1.add(btHoaDon);
        btHoaDon.setBounds(100, 270, 170, 90);

        btThucDon.setBackground(new java.awt.Color(255, 255, 255));
        btThucDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/MENU.png"))); // NOI18N
        btThucDon.setText("QUẢN LÍ \nTHỰC ĐƠN");
        btThucDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThucDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThucDonActionPerformed(evt);
            }
        });
        jPanel1.add(btThucDon);
        btThucDon.setBounds(100, 160, 170, 90);

        btBan.setBackground(new java.awt.Color(255, 255, 255));
        btBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/bàn.png"))); // NOI18N
        btBan.setText("QUẢN LÍ  BÀN");
        btBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanActionPerformed(evt);
            }
        });
        jPanel1.add(btBan);
        btBan.setBounds(280, 160, 170, 90);

        btKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        btKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/khachhang.png"))); // NOI18N
        btKhachHang.setText("QUẢN LÍ  KHÁCH HÀNG");
        btKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKhachHangActionPerformed(evt);
            }
        });
        jPanel1.add(btKhachHang);
        btKhachHang.setBounds(280, 270, 170, 90);

        btThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/thongke.png"))); // NOI18N
        btThongKe.setText("THỐNG KÊ");
        btThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btThongKe);
        btThongKe.setBounds(460, 270, 170, 90);

        btOrder.setBackground(new java.awt.Color(255, 255, 255));
        btOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/186530842_758452454851125_5698688404055718619_n.png"))); // NOI18N
        btOrder.setText("ORDER");
        btOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btOrder);
        btOrder.setBounds(280, 380, 170, 90);

        btVoucher.setBackground(new java.awt.Color(255, 255, 255));
        btVoucher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/voucher.png"))); // NOI18N
        btVoucher.setText("QUẢN LÍ  VOUCHER");
        btVoucher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoucher.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoucherActionPerformed(evt);
            }
        });
        jPanel1.add(btVoucher);
        btVoucher.setBounds(460, 160, 170, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/3235.jpg_wh860.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThucDonActionPerformed
        QLSP qlsp = new QLSP();
        qlsp.setVisible(true);
        qlsp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btThucDonActionPerformed

    private void btBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanActionPerformed
        BanAn banAn = new BanAn();
        banAn.setVisible(true);
        banAn.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btBanActionPerformed

    private void btVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoucherActionPerformed
        QLVoucher qLVoucher = new QLVoucher();
        qLVoucher.setVisible(true);
        qLVoucher.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btVoucherActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        QLHoaDon qLHoaDon = new QLHoaDon();
        qLHoaDon.setVisible(true);
        qLHoaDon.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKhachHangActionPerformed
        QLKhachHang qLKhachHang = new QLKhachHang();
        qLKhachHang.setVisible(true);
        qLKhachHang.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btKhachHangActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        thongKe tk = new thongKe();
        tk.setVisible(true);
        tk.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btThongKeActionPerformed

    private void btOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrderActionPerformed
        BanAn_MangVe bamv = new BanAn_MangVe();
        bamv.setVisible(true);
        bamv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrangChu tc  = new TrangChu();
                tc.setVisible(true);
                tc.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBan;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btKhachHang;
    private javax.swing.JButton btOrder;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btThucDon;
    private javax.swing.JButton btVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
